### ISSUE TITLE
Darwinia ponder cannot be recovered due to a database error

### ISSUE THREAD

**Issue by jiguantong** [msgport/ormponder#55]
```
ormponder-darwinia  | 7:14:11 AM INFO  app        Indexed 2639 events
ormponder-darwinia  | 7:14:12 AM INFO  app        Indexed 1016 events
ormponder-darwinia  | 7:14:13 AM WARN  sync       Failed 'insertLogs' database method after '10' attempts
ormponder-darwinia  | error: ON CONFLICT DO UPDATE command cannot affect row a second time
ormponder-darwinia  |     at /app/node_modules/pg/lib/client.js:535:17
ormponder-darwinia  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ormponder-darwinia  |     at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:69:28)
ormponder-darwinia  |     at PostgresConnection.connection.executeQuery (file:///app/node_modules/kysely/dist/esm/driver/runtime-driver.js:89:24)
ormponder-darwinia  |     at file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
ormponder-darwinia  |     at DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
ormponder-darwinia  |     at DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
ormponder-darwinia  |     at InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:515:24)
ormponder-darwinia  |     at file:///app/node_modules/@ponder/core/src/sync-store/index.ts:560:9
ormponder-darwinia  |     at HeadlessKysely.wrap (file:///app/node_modules/@ponder/core/src/database/kysely.ts:42:24)
ormponder-darwinia  |     at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:88:41)
ormponder-darwinia  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ormponder-darwinia  |     at PostgresConnection.connection.executeQuery (file:///app/node_modules/kysely/dist/esm/driver/runtime-driver.js:89:24)
ormponder-darwinia  |     at file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
ormponder-darwinia  |     at DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
ormponder-darwinia  |     at DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
ormponder-darwinia  |     at InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:515:24)
ormponder-darwinia  |     at file:///app/node_modules/@ponder/core/src/sync-store/index.ts:560:9
ormponder-darwinia  |     at HeadlessKysely.wrap (file:///app/node_modules/@ponder/core/src/database/kysely.ts:42:24)
ormponder-darwinia  |     at Object.insertLogs (file:///app/node_modules/@ponder/core/src/sync-store/index.ts:542:5)
ormponder-darwinia  | 7:14:13 AM ERROR sync       Fatal error: Unable to sync 'darwinia' from 4958466 to 4958491.
ormponder-darwinia  | error: ON CONFLICT DO UPDATE command cannot affect row a second time
ormponder-darwinia  |     at /app/node_modules/pg/lib/client.js:535:17
ormponder-darwinia  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ormponder-darwinia  |     at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:69:28)
ormponder-darwinia  |     at PostgresConnection.connection.executeQuery (file:///app/node_modules/kysely/dist/esm/driver/runtime-driver.js:89:24)
ormponder-darwinia  |     at file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
ormponder-darwinia  |     at DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
ormponder-darwinia  |     at DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
ormponder-darwinia  |     at InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:515:24)
ormponder-darwinia  |     at file:///app/node_modules/@ponder/core/src/sync-store/index.ts:560:9
ormponder-darwinia  |     at HeadlessKysely.wrap (file:///app/node_modules/@ponder/core/src/database/kysely.ts:42:24)
ormponder-darwinia  |     at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:88:41)
ormponder-darwinia  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ormponder-darwinia  |     at PostgresConnection.connection.executeQuery (file:///app/node_modules/kysely/dist/esm/driver/runtime-driver.js:89:24)
ormponder-darwinia  |     at file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
ormponder-darwinia  |     at DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
ormponder-darwinia  |     at DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
ormponder-darwinia  |     at InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:515:24)
ormponder-darwinia  |     at file:///app/node_modules/@ponder/core/src/sync-store/index.ts:560:9
ormponder-darwinia  |     at HeadlessKysely.wrap (file:///app/node_modules/@ponder/core/src/database/kysely.ts:42:24)
ormponder-darwinia  |     at Object.insertLogs (file:///app/node_modules/@ponder/core/src/sync-store/index.ts:542:5)
ormponder-darwinia  | 7:14:13 AM WARN  process    Received fatal error, starting shutdown sequence
ormponder-darwinia  | 7:14:13 AM FATAL process    Finished shutdown sequence, terminating (exit code 1)
```

**Comment by jiguantong** [comment]
Events in 4958466 to 4958491

https://darwinia.subscan.io/extrinsic/4958472-2
https://darwinia.subscan.io/extrinsic/4958468-2
https://darwinia.subscan.io/extrinsic/4958485-2
https://darwinia.subscan.io/extrinsic/4958487-2

**Comment by jiguantong** [comment]
If I skip the above blocks, the new blocks will have problems again

Fatal error: Unable to sync 'darwinia' from 4961928 to 4965384.

```
ormponder-darwinia  | 7:51:08 AM WARN  sync       Failed 'insertLogs' database method after '10' attempts
ormponder-darwinia  | error: ON CONFLICT DO UPDATE command cannot affect row a second time
ormponder-darwinia  |     at /app/node_modules/pg/lib/client.js:535:17
ormponder-darwinia  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ormponder-darwinia  |     at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:69:28)
ormponder-darwinia  |     at PostgresConnection.connection.executeQuery (file:///app/node_modules/kysely/dist/esm/driver/runtime-driver.js:89:24)
ormponder-darwinia  |     at file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
ormponder-darwinia  |     at DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
ormponder-darwinia  |     at DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
ormponder-darwinia  |     at InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:515:24)
ormponder-darwinia  |     at file:///app/node_modules/@ponder/core/src/sync-store/index.ts:560:9
ormponder-darwinia  |     at HeadlessKysely.wrap (file:///app/node_modules/@ponder/core/src/database/kysely.ts:42:24)
ormponder-darwinia  |     at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:88:41)
ormponder-darwinia  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ormponder-darwinia  |     at PostgresConnection.connection.executeQuery (file:///app/node_modules/kysely/dist/esm/driver/runtime-driver.js:89:24)
ormponder-darwinia  |     at file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
ormponder-darwinia  |     at DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
ormponder-darwinia  |     at DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
ormponder-darwinia  |     at InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:515:24)
ormponder-darwinia  |     at file:///app/node_modules/@ponder/core/src/sync-store/index.ts:560:9
ormponder-darwinia  |     at HeadlessKysely.wrap (file:///app/node_modules/@ponder/core/src/database/kysely.ts:42:24)
ormponder-darwinia  |     at Object.insertLogs (file:///app/node_modules/@ponder/core/src/sync-store/index.ts:542:5)
ormponder-darwinia  | 7:51:08 AM ERROR sync       Fatal error: Unable to sync 'darwinia' from 4961928 to 4965384.
ormponder-darwinia  | error: ON CONFLICT DO UPDATE command cannot affect row a second time
ormponder-darwinia  |     at /app/node_modules/pg/lib/client.js:535:17
ormponder-darwinia  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ormponder-darwinia  |     at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:69:28)
ormponder-darwinia  |     at PostgresConnection.connection.executeQuery (file:///app/node_modules/kysely/dist/esm/driver/runtime-driver.js:89:24)
ormponder-darwinia  |     at file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
ormponder-darwinia  |     at DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
ormponder-darwinia  |     at DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
ormponder-darwinia  |     at InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:515:24)
ormponder-darwinia  |     at file:///app/node_modules/@ponder/core/src/sync-store/index.ts:560:9
ormponder-darwinia  |     at HeadlessKysely.wrap (file:///app/node_modules/@ponder/core/src/database/kysely.ts:42:24)
ormponder-darwinia  |     at PostgresConnection.executeQuery (file:///app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:88:41)
ormponder-darwinia  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
ormponder-darwinia  |     at PostgresConnection.connection.executeQuery (file:///app/node_modules/kysely/dist/esm/driver/runtime-driver.js:89:24)
ormponder-darwinia  |     at file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:35:28
ormponder-darwinia  |     at DefaultConnectionProvider.provideConnection (file:///app/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)
ormponder-darwinia  |     at DefaultQueryExecutor.executeQuery (file:///app/node_modules/kysely/dist/esm/query-executor/query-executor-base.js:34:16)
ormponder-darwinia  |     at InsertQueryBuilder.execute (file:///app/node_modules/kysely/dist/esm/query-builder/insert-query-builder.js:515:24)
ormponder-darwinia  |     at file:///app/node_modules/@ponder/core/src/sync-store/index.ts:560:9
ormponder-darwinia  |     at HeadlessKysely.wrap (file:///app/node_modules/@ponder/core/src/database/kysely.ts:42:24)
ormponder-darwinia  |     at Object.insertLogs (file:///app/node_modules/@ponder/core/src/sync-store/index.ts:542:5)
ormponder-darwinia  | 7:51:08 AM WARN  process    Received fatal error, starting shutdown sequence
ormponder-darwinia  | 7:51:08 AM FATAL process    Finished shutdown sequence, terminating (exit code 1)
```

**Comment by jiguantong** [comment]
https://github.com/ponder-sh/ponder/issues/1374

**Comment by jiguantong** [comment]
My local logs, 

![image](https://github.com/user-attachments/assets/4c627487-9452-4093-be01-0bb2f46ff205)

```
1:46:19 PM INFO  app        Indexed 148 events
1:46:19 PM ERROR sync       Fatal error: Unable to sync 'darwinia' from 4939466 to 4939491.
Error: Detected inconsistent RPC responses. 'log.blockHash' 0xcede5dc66c4d37eaf24e3e6c1c509372ecea41a926d2f715fb5ad026a2bde63a, {"address":"0x13b2211a7ca45db2808f6db05557ce5347e3634e","topics":["0xa931ec14fe958397dcb26e285e56292c13d77907712b51bbaa24cfc9349b789d","0x000000000000000000000000be01b76ab454ae2497ae43168b1f70c92ac1c726"],"data":"0x000000000000000000000000000000000000000000000000000000000000002c00000000000000000000000013b2211a7ca45db2808f6db05557ce5347e3634e00000000000000000000000000000000000000000000000000000000000008c6341d5c17e68bef0e4a51ea5e9b4b85a884aa895c7dfabe7df48420e0684f9a55","blockHash":"0xcede5dc66c4d37eaf24e3e6c1c509372ecea41a926d2f715fb5ad026a2bde63a","blockNumber":"0x4b5ee0","transactionHash":"0xc6a795c8ee553a0722b0a598352277659962509046e8d15d2d16bd9c34305c63","transactionIndex":"0x0","logIndex":"0x0","transactionLogIndex":"0x0","removed":false} does not match 'block.hash' 0x7049eab28057b29de29afe380b0d42f27942e2b97441c898d14c046c1f1a8af8, {"author":"0x6940858e29c662cd135981fb476c3974d8720bcb","baseFeePerGas":"0x118b677080","difficulty":"0x0","extraData":"0x","gasLimit":"0x1312d00","gasUsed":"0x0","hash":"0x7049eab28057b29de29afe380b0d42f27942e2b97441c898d14c046c1f1a8af8","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x6940858e29c662cd135981fb476c3974d8720bcb","nonce":"0x0000000000000000","number":"0x4b5ee0","parentHash":"0xfd25b8edc566037d3f99ff17b227fc46ca52e85bf8509ddfba4413d4b08dc317","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x202","stateRoot":"0x289f92d1bacf0cce5c0fa02f308e83e581d9302e3f3221fbfdd21b9cc3f58f62","timestamp":"0x67591fb0","totalDifficulty":"0x0","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}
    at syncLogFilter (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync-historical/index.ts:235:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync-historical/index.ts:514:21
    at async Promise.all (index 0)
    at file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync-historical/index.ts:506:13
    at async Promise.all (index 0)
    at Object.sync (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync-historical/index.ts:472:7)
    at localHistoricalSyncGenerator (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync/index.ts:1154:23)
    at file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/utils/generators.ts:13:19
1:46:19 PM WARN  process    Received fatal error, starting shutdown sequence
```

**Comment by fewensa** [comment]
Tried upgrade #58 and completed, did fix the issue, but ponder resync was a disaster, ended up switching to indexing scheme #59 so this is no longer an issue
